name = "streamdeck"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true
routes = ["streamdeck.geostyx.com/*"]

[placement]
mode = "off"

[vars]
NAME = "streamdeck"
ENVIRONMENT = "production"
AXIOM_DATASET = "workers"
AXIOM_DATASET_OTEL = "workers-otel"

# [secrets]
# API_TOKEN: 1P-ge7dk

[durable_objects]
bindings = [{ name = "MUTEXFETCHER", class_name = "MutexFetcher" }]

[[migrations]]
tag = "v1"
new_classes = ["MutexFetcher"]
